### PR TITLE
Some refactor

### PR DESCRIPTION
**Pull request by cilinder**

### CODE REVIEW

**Review by sinhp — COMMENTED** [review]
the changes in the first file `Basic.lean` are not paradigmatic of the mathlib style. Going forward, I think it would be easier to do PR one file at a time. Thanks!

**Comment by digama0** [comment]
Could you be more specific @sinhp ? Both before and after are not quite mathlib style (the indentation is 2 space instead of 4 space in some theorem statements) but it does seem to be an improvement in most cases.

**Comment by awodey** [comment]
can we have a meeting sometime to bring everyone up to date ?
are Emily and Sina back in Bonn yet?
I’m home now and could do some work on this.

Steve

**Comment by digama0** [comment]
> are Emily and Sina back in Bonn yet?

Yes. This week is a conference week so I'm not sure how much free time we will have without shorting some other session, but I will see how long they are around and maybe we can meet tomorrow afternoon/evening, or next week.

**Comment by awodey** [comment]
Maybe next week would be better?On Jul 10, 2024, at 19:33, Mario Carneiro ***@***.***> wrote:﻿

are Emily and Sina back in Bonn yet?

Yes. This week is a conference week so I'm not sure how much free time we will have without shorting some other session, but I will see how long they are around and maybe we can meet tomorrow afternoon/evening, or next week.

**Comment by sinhp** [comment]
> Could you be more specific @sinhp ? Both before and after are not quite mathlib style (the indentation is 2 space instead of 4 space in some theorem statements) but it does seem to be an improvement in most cases.

can you point to one of the places where the style is incorrect? 
Mathlib documentation page (If the theorem statement requires multiple lines, indent the subsequent lines by 4 spaces. ) guide says

1. After stating the theorem, we indent the lines in the subsequent proof by 2 spaces.
2. If the theorem statement requires multiple lines, indent the subsequent lines by _4 spaces_.

**Comment by sinhp** [comment]
the conflicts have been manually resolved.

**Pull request closed without merging**
